name="Atir Khan";
school="Crescent High School";
std="10th";
sec="B";
no=255;
x=80;
y=76;
z=90;
console.log("...............................................");
console.log("         "+school);
console.log("...............................................");
console.log(name+"        "+"Roll No-"+no+"        "+std+" "+sec);
console.log("_______________________________________________");
console.log("subject      |     Marks");
console.log("_______________________________________________");
console.log("Maths        |      "+x);
console.log("Science      |      "+y);
console.log("Physics      |      "+z);
console.log("_______________________________________________");